//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManageStudentsV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lop_hoc_phan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Lop_hoc_phan()
        {
            this.Lich_hoc = new HashSet<Lich_hoc>();
            this.Hoc_sinh = new HashSet<Hoc_sinh>();
            this.Giao_vien = new HashSet<Giao_vien>();
        }
    
        public int ma_hoc_phan { get; set; }
        public Nullable<int> ma_lop { get; set; }
        public Nullable<int> ma_mon { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Lich_hoc> Lich_hoc { get; set; }
        public virtual Lop_chinh Lop_chinh { get; set; }
        public virtual Mon_hoc Mon_hoc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hoc_sinh> Hoc_sinh { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Giao_vien> Giao_vien { get; set; }
    }
}
