//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page__ManageStudentHome_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page__ManageStudentHome_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\bamec\AppData\Local\Temp\8B1CAFBA03C6C677CF2E000EC0E58092CEA9\2\ManageStudentsV2\ManageStudentsV2\Views\Shared\_ManageStudentHome.cshtml"
      __o = ViewBag.Title;


#line default
#line hidden

#line 2 "C:\Users\bamec\AppData\Local\Temp\8B1CAFBA03C6C677CF2E000EC0E58092CEA9\2\ManageStudentsV2\ManageStudentsV2\Views\Shared\_ManageStudentHome.cshtml"
__o = Styles.Render("~/Content/css");


#line default
#line hidden

#line 3 "C:\Users\bamec\AppData\Local\Temp\8B1CAFBA03C6C677CF2E000EC0E58092CEA9\2\ManageStudentsV2\ManageStudentsV2\Views\Shared\_ManageStudentHome.cshtml"
__o = Scripts.Render("~/bundles/modernizr");


#line default
#line hidden

#line 4 "C:\Users\bamec\AppData\Local\Temp\8B1CAFBA03C6C677CF2E000EC0E58092CEA9\2\ManageStudentsV2\ManageStudentsV2\Views\Shared\_ManageStudentHome.cshtml"
       __o = Html.ActionLink("Application name", "Index", "ManageStudentHome", new { area = "" }, new { @class = "navbar-brand" });


#line default
#line hidden

#line 5 "C:\Users\bamec\AppData\Local\Temp\8B1CAFBA03C6C677CF2E000EC0E58092CEA9\2\ManageStudentsV2\ManageStudentsV2\Views\Shared\_ManageStudentHome.cshtml"
                   __o = Html.ActionLink("Home", "Index", "ManageStudentHome", new { area = "" }, new { @class = "nav-link" });


#line default
#line hidden

#line 6 "C:\Users\bamec\AppData\Local\Temp\8B1CAFBA03C6C677CF2E000EC0E58092CEA9\2\ManageStudentsV2\ManageStudentsV2\Views\Shared\_ManageStudentHome.cshtml"
                   __o = Html.ActionLink("Lop Hoc", "Index", "Lop_chinh", new { area = "" }, new { @class = "nav-link" });


#line default
#line hidden

#line 7 "C:\Users\bamec\AppData\Local\Temp\8B1CAFBA03C6C677CF2E000EC0E58092CEA9\2\ManageStudentsV2\ManageStudentsV2\Views\Shared\_ManageStudentHome.cshtml"
                   __o = Html.ActionLink("Khoa", "Index", "Khoa", new { area = "" }, new { @class = "nav-link" });


#line default
#line hidden

#line 8 "C:\Users\bamec\AppData\Local\Temp\8B1CAFBA03C6C677CF2E000EC0E58092CEA9\2\ManageStudentsV2\ManageStudentsV2\Views\Shared\_ManageStudentHome.cshtml"
                   __o = Html.ActionLink("Nganh", "Index", "Nganh", new { area = "" }, new { @class = "nav-link" });


#line default
#line hidden

#line 9 "C:\Users\bamec\AppData\Local\Temp\8B1CAFBA03C6C677CF2E000EC0E58092CEA9\2\ManageStudentsV2\ManageStudentsV2\Views\Shared\_ManageStudentHome.cshtml"
                   __o = Html.ActionLink("Giao vien", "Index", "Giao_vien", new { area = "" }, new { @class = "nav-link" });


#line default
#line hidden

#line 10 "C:\Users\bamec\AppData\Local\Temp\8B1CAFBA03C6C677CF2E000EC0E58092CEA9\2\ManageStudentsV2\ManageStudentsV2\Views\Shared\_ManageStudentHome.cshtml"
                   __o = Html.ActionLink("Nien khoa", "Index", "Nien_khoa", new { area = "" }, new { @class = "nav-link" });


#line default
#line hidden

#line 11 "C:\Users\bamec\AppData\Local\Temp\8B1CAFBA03C6C677CF2E000EC0E58092CEA9\2\ManageStudentsV2\ManageStudentsV2\Views\Shared\_ManageStudentHome.cshtml"
                   __o = Html.ActionLink("Mon hoc", "Index", "Mon_+hoc", new { area = "" }, new { @class = "nav-link" });


#line default
#line hidden

#line 12 "C:\Users\bamec\AppData\Local\Temp\8B1CAFBA03C6C677CF2E000EC0E58092CEA9\2\ManageStudentsV2\ManageStudentsV2\Views\Shared\_ManageStudentHome.cshtml"
                   __o = Html.ActionLink("Diem", "Index", "Diem", new { area = "" }, new { @class = "nav-link" });


#line default
#line hidden

#line 13 "C:\Users\bamec\AppData\Local\Temp\8B1CAFBA03C6C677CF2E000EC0E58092CEA9\2\ManageStudentsV2\ManageStudentsV2\Views\Shared\_ManageStudentHome.cshtml"
                   __o = Html.ActionLink("Hoc sinh", "Index", "Hoc_sinh", new { area = "" }, new { @class = "nav-link" });


#line default
#line hidden

#line 14 "C:\Users\bamec\AppData\Local\Temp\8B1CAFBA03C6C677CF2E000EC0E58092CEA9\2\ManageStudentsV2\ManageStudentsV2\Views\Shared\_ManageStudentHome.cshtml"
                   __o = Html.ActionLink("Lop hoc phan", "Index", "Lop_hoc_phan", new { area = "" }, new { @class = "nav-link" });


#line default
#line hidden

#line 15 "C:\Users\bamec\AppData\Local\Temp\8B1CAFBA03C6C677CF2E000EC0E58092CEA9\2\ManageStudentsV2\ManageStudentsV2\Views\Shared\_ManageStudentHome.cshtml"
   __o = RenderBody();


#line default
#line hidden

#line 16 "C:\Users\bamec\AppData\Local\Temp\8B1CAFBA03C6C677CF2E000EC0E58092CEA9\2\ManageStudentsV2\ManageStudentsV2\Views\Shared\_ManageStudentHome.cshtml"
                 __o = DateTime.Now.Year;


#line default
#line hidden

#line 17 "C:\Users\bamec\AppData\Local\Temp\8B1CAFBA03C6C677CF2E000EC0E58092CEA9\2\ManageStudentsV2\ManageStudentsV2\Views\Shared\_ManageStudentHome.cshtml"
__o = Scripts.Render("~/bundles/jquery");


#line default
#line hidden

#line 18 "C:\Users\bamec\AppData\Local\Temp\8B1CAFBA03C6C677CF2E000EC0E58092CEA9\2\ManageStudentsV2\ManageStudentsV2\Views\Shared\_ManageStudentHome.cshtml"
__o = Scripts.Render("~/bundles/bootstrap");


#line default
#line hidden

#line 19 "C:\Users\bamec\AppData\Local\Temp\8B1CAFBA03C6C677CF2E000EC0E58092CEA9\2\ManageStudentsV2\ManageStudentsV2\Views\Shared\_ManageStudentHome.cshtml"
__o = RenderSection("scripts", required: false);


#line default
#line hidden
}
}
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page__ManageStudentHome_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page__ManageStudentHome_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\bamec\AppData\Local\Temp\560AE49A8664D954B58A357A594FAAAF8CC7\2\ManageStudentsV2\ManageStudentsV2\Views\Shared\_ManageStudentHome.cshtml"
      __o = ViewBag.Title;


#line default
#line hidden

#line 2 "C:\Users\bamec\AppData\Local\Temp\560AE49A8664D954B58A357A594FAAAF8CC7\2\ManageStudentsV2\ManageStudentsV2\Views\Shared\_ManageStudentHome.cshtml"
__o = Styles.Render("~/Content/css");


#line default
#line hidden

#line 3 "C:\Users\bamec\AppData\Local\Temp\560AE49A8664D954B58A357A594FAAAF8CC7\2\ManageStudentsV2\ManageStudentsV2\Views\Shared\_ManageStudentHome.cshtml"
__o = Scripts.Render("~/bundles/modernizr");


#line default
#line hidden

#line 4 "C:\Users\bamec\AppData\Local\Temp\560AE49A8664D954B58A357A594FAAAF8CC7\2\ManageStudentsV2\ManageStudentsV2\Views\Shared\_ManageStudentHome.cshtml"
       __o = Html.ActionLink("Hệ Thống Quản Lý Sinh Viên 2.0", "Index", "ManageStudentHome", new { area = "" }, new { @class = "navbar-brand" });


#line default
#line hidden

#line 5 "C:\Users\bamec\AppData\Local\Temp\560AE49A8664D954B58A357A594FAAAF8CC7\2\ManageStudentsV2\ManageStudentsV2\Views\Shared\_ManageStudentHome.cshtml"
                   __o = Html.ActionLink("Home", "Index", "ManageStudentHome", new { area = "" }, new { @class = "nav-link" });


#line default
#line hidden

#line 6 "C:\Users\bamec\AppData\Local\Temp\560AE49A8664D954B58A357A594FAAAF8CC7\2\ManageStudentsV2\ManageStudentsV2\Views\Shared\_ManageStudentHome.cshtml"
                   __o = Html.ActionLink("Class", "ClassView", "ManageStudentHome", new { area = "" }, new { @class = "nav-link" });


#line default
#line hidden

#line 7 "C:\Users\bamec\AppData\Local\Temp\560AE49A8664D954B58A357A594FAAAF8CC7\2\ManageStudentsV2\ManageStudentsV2\Views\Shared\_ManageStudentHome.cshtml"
                   __o = Html.ActionLink("login", "Login", "Admin", new { area = "" }, new { @class = "nav-link" });


#line default
#line hidden

#line 8 "C:\Users\bamec\AppData\Local\Temp\560AE49A8664D954B58A357A594FAAAF8CC7\2\ManageStudentsV2\ManageStudentsV2\Views\Shared\_ManageStudentHome.cshtml"
   __o = RenderBody();


#line default
#line hidden

#line 9 "C:\Users\bamec\AppData\Local\Temp\560AE49A8664D954B58A357A594FAAAF8CC7\2\ManageStudentsV2\ManageStudentsV2\Views\Shared\_ManageStudentHome.cshtml"
                 __o = DateTime.Now.Year;


#line default
#line hidden

#line 10 "C:\Users\bamec\AppData\Local\Temp\560AE49A8664D954B58A357A594FAAAF8CC7\2\ManageStudentsV2\ManageStudentsV2\Views\Shared\_ManageStudentHome.cshtml"
__o = Scripts.Render("~/bundles/jquery");


#line default
#line hidden

#line 11 "C:\Users\bamec\AppData\Local\Temp\560AE49A8664D954B58A357A594FAAAF8CC7\2\ManageStudentsV2\ManageStudentsV2\Views\Shared\_ManageStudentHome.cshtml"
__o = Scripts.Render("~/bundles/bootstrap");


#line default
#line hidden

#line 12 "C:\Users\bamec\AppData\Local\Temp\560AE49A8664D954B58A357A594FAAAF8CC7\2\ManageStudentsV2\ManageStudentsV2\Views\Shared\_ManageStudentHome.cshtml"
__o = RenderSection("scripts", required: false);


#line default
#line hidden
}
}
}
